/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ExecuteRunRequest {
    /**
    * Trigger event.
    */
    'trigger': ExecuteRunRequest.TriggerEnum;
    /**
    * Message schema
    */
    'message': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "trigger",
            "baseName": "trigger",
            "type": "ExecuteRunRequest.TriggerEnum"
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ExecuteRunRequest.attributeTypeMap;
    }
}

export namespace ExecuteRunRequest {
    export enum TriggerEnum {
        CartUpdateRequested = <any> 'CartUpdateRequested',
        InvoiceUpdateRequested = <any> 'InvoiceUpdateRequested'
    }
}
