/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ExecuteRunFunctionResponse {
    /**
    * The error response
    */
    'name': string;
    /**
    * The error response
    */
    'extensionExecutionError': boolean;
    /**
    * Response
    */
    'response': object | null;
    /**
    * The error response
    */
    'error': string | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "extensionExecutionError",
            "baseName": "extensionExecutionError",
            "type": "boolean"
        },
        {
            "name": "response",
            "baseName": "response",
            "type": "object"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ExecuteRunFunctionResponse.attributeTypeMap;
    }
}

