/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ExtensibilityFunctionRequest {
    /**
    * The name of the executable code.
    */
    'name': string;
    /**
    * The description of the executable code.
    */
    'description': string;
    /**
    * The event that triggers this workflow.
    */
    'trigger': ExtensibilityFunctionRequest.TriggerEnum;
    /**
    * The code that will run for steps with this external name.
    */
    'code': string;
    /**
    * Object version
    */
    'versionId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "trigger",
            "baseName": "trigger",
            "type": "ExtensibilityFunctionRequest.TriggerEnum"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ExtensibilityFunctionRequest.attributeTypeMap;
    }
}

export namespace ExtensibilityFunctionRequest {
    export enum TriggerEnum {
        CartUpdateRequested = <any> 'CartUpdateRequested',
        InvoiceUpdateRequested = <any> 'InvoiceUpdateRequested'
    }
}
