/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ExtensibilityFunctionResponse {
    /**
    * ID
    */
    'extensibilityFunctionId': string;
    /**
    * The name of the executable code.
    */
    'name': string;
    /**
    * Version ID
    */
    'versionId': string;
    /**
    * Description.
    */
    'description': string;
    /**
    * The code that the requested step runs.
    */
    'code': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "extensibilityFunctionId",
            "baseName": "extensibilityFunctionId",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "versionId",
            "baseName": "versionId",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ExtensibilityFunctionResponse.attributeTypeMap;
    }
}

