/**
 * ManageSpace Extensibility API
 * ManageSpace Extensibility API Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class TestExtensionRequest {
    /**
    * Extension name.
    */
    'name': string;
    /**
    * Initial data(if first step).
    */
    'initialData'?: object;
    /**
    * State.
    */
    'state'?: object;
    /**
    * Ports (optional project steps).
    */
    'ports'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "initialData",
            "baseName": "initialData",
            "type": "object"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "object"
        },
        {
            "name": "ports",
            "baseName": "ports",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return TestExtensionRequest.attributeTypeMap;
    }
}

